### ISSUE TITLE
compile bugs in nn

### ISSUE THREAD

**Issue by cuge1995** [sh8/RePOSE#2]
```
gcc: error: src/nearest_neighborhood.cu.o: No such file or directory
gcc: error: /opt/cuda-10.1/lib64/libcudart.so: No such file or directory
```

**Comment by sh8** [comment]
Please use your CUDA path. The current CUDA path is `/opt/cuda-10.1/` but you need to change it.

**Comment by cuge1995** [comment]
this bug `gcc: error: src/nearest_neighborhood.cu.o: No such file or directory` still exist.

**Comment by sh8** [comment]
I think the compilation process is still failed so you should check whether you could compile the CUDA file correctly or not.

**Comment by cuge1995** [comment]
but how?

**Comment by sh8** [comment]
I honestly have no idea what's going on just from this log. I checked this again in my environment and it worked without a problem. If you modify the path correctly, the compilation process should work. Could you provide the command you ran and stack trace? Then, I think I can help you debug the error!

**Comment by sh8** [comment]
The code is borrowed from [here](https://github.com/zju3dv/clean-pvnet/tree/master/lib/csrc/nn). You may be able to find an answer in the repository.

**Comment by sh8** [comment]
Can you make sure you have CUDA and libcudart.so?
