### ISSUE TITLE
Question about the PVNet result

### ISSUE THREAD

**Issue by rcao-hk** [sh8/RePOSE#3]
Hi,

Thank you for your excellent work!
I am a little confused about the PVNet's initial pose for LINEMOD and LINEMOD Occlusion. How could I find them? 

Also, for the initial pose result in YCB-V based on PoseCNN you used, how could I find it?

Best,
Rui

**Comment by sh8** [comment]
Hi Rui!

Thank you for your interest in our work!

> I am a little confused about the PVNet's initial pose for LINEMOD and LINEMOD Occlusion. How could I find them?

You can get the initial pose simply by running the pre-trained model provided in [the clean-pvnet repository](https://github.com/zju3dv/clean-pvnet).

> Also, for the initial pose result in YCB-V based on PoseCNN you used, how could I find it?

I think I downloaded the result from [this link](https://drive.google.com/file/d/1OQ__c4BBv5wn8B3NgK80JfGOhxiCjWZj/view?usp=sharing) in the repository [DeepIM-Pytorch](https://github.com/NVlabs/DeepIM-PyTorch). I confirmed that the result corresponded to the one in the paper, but I recommend you to do it yourself again just in case.

Best,
Shun

**Comment by rcao-hk** [comment]
Hi,

Could you please report the result when the initial pose is from the PoseCNN? 

Best,
Rui

**Comment by sh8** [comment]
Hi Rui!

Unfortunately, I don't have the numbers using the initial poses from PoseCNN.
I think [the follow-up work](https://arxiv.org/abs/2203.12870) of this paper reported the numbers. Nevertheless, no experimental details are given and the performance of RePOSE largely changes depending on the initial poses it's training on, so I can not assure their numbers are correct.

Best,
Shun
