### ISSUE TITLE
Question about "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by ldylab** [sh8/RePOSE#4]
Hi, thank you for your awesome work! But when I try to run the command "pip install -r requirements.txt", and it just shows that

 "ERROR: git+git@github.com:sh8/rdopt.git@7601bca4818a03ef1ace1e0c1df396ccec56003f#egg=camera_jacobian is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file)." 

How could I fix this? Thank you very much!

**Comment by sh8** [comment]
Hi! Thank you for your interest in this project!
`camera_jacobioan` is an internal library so you can install it by the following command :+1: 
```
ROOT=/path/to/RePOSE
cd $ROOT/lib/csrc/camera_jacobian
python setup.py build_ext --inplace
```
I removed the line to avoid confusion just in case. If you have additional questions, please feel free to reopen this issue!
