### ISSUE TITLE
Occ-Linemod initial results

### ISSUE THREAD

**Issue by YangHai-1218** [sh8/RePOSE#6]
Hi, this is a great work.
As you metioned in the paper, you did experiments on Occ-Linemod, using the pvnet results as the initial pose. Can you please share the pvnet initial result? Any format is okay, Thanks.

**Comment by sh8** [comment]
Thank you for your interest in our work!

The link is in README.md but let me put it here just in case! The files of `[0-9]{4}.npy` contain the initial poses (`x_ini` is the key name). https://drive.google.com/drive/u/1/folders/1ufM_-qkQqqWUY0H0PV1fQGL1GYluksKz

Best regards,
Shun

**Comment by YangHai-1218** [comment]
Sorry to bother you again. 
But I am a little confused by the initial poses. It is very different from the ground truth. For example, for ape in frame 1, the provided initial pose is `[-1.1688580e-01,  1.1876651e+00,  1.7402347e+00,  1.7772609e-02,
        7.4241700e-04,  1.1550709e-02]`, but the ground truth is `{"cam_R_m2c": [0.79796083, 0.6023787, -0.02630684, 0.38035542, -0.53676251, -0.7533023, -0.46784284, 0.59102839, -0.65733923], "cam_t_m2c": [183.63633301, -131.49685045, 1147.30061109], "obj_id": 1}`.  
I know the first three number is the rotation angles, but I can't see the relationship between the last three number and the cam_t_m2c. 
Could you please explain a little bit for me? Thanks!

**Comment by yangxingjian** [comment]
@YangHai-1218 Hello, are you able to figure out the relation between x[3:] and the cam_t_m2c?
