### ISSUE TITLE
Questions about requirements.txt

### ISSUE THREAD

**Issue by parkjaewoo0611** [sh8/RePOSE#9]
Hi! Thanks for your great works

I have one question.

I got this error from "pip install -r requirements.txt"
ERROR: Could not find a version that satisfies the requirement soft-renderer==1.0.0 (from versions: none)
ERROR: No matching distribution found for soft-renderer==1.0.0

and I cannot find any package name "soft-renderer" in pypi either. 

What should I do?

**Comment by barvin04** [comment]
Hi @sh8 , 
I too am facing this issue. Can please throw some light on it? 

Thanks

**Comment by sh8** [comment]
Hi,

I'm sorry for the slow reply. Actually, RePOSE doesn't use soft-renderer, so you can simply remove the line in requirements.txt! I also updated this repository.

Thanks!
